In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('../price.csv')

pd.DataFrame({"dt":[9:30;9.40]})

In [5]:
df

,date,sector,close,open,high,low,volume,turnover,outstanding
0,2020-08-26,2025规划,17.099342,17.376184,17.710921,16.897105,21750333.0,3.160960e+10,7.363291e+07
1,2020-08-26,3D打印,16.533333,16.953556,17.242000,16.352889,7332533.0,8.609245e+09,3.855253e+07
2,2020-08-26,3D摄像头,32.694000,33.891000,34.307000,32.424000,4176112.0,1.155246e+10,1.723285e+07
3,2020-08-26,3D玻璃,11.558947,11.913158,12.069474,11.425263,8603472.0,1.069712e+10,4.500931e+07
4,2020-08-26,5G概念,20.043140,20.668217,20.945078,19.853488,53489373.0,8.487718e+10,3.117830e+08
...,...,...,...,...,...,...,...,...,...
351142,2023-08-25,鸡肉概念,14.696667,14.840000,15.432222,14.550000,3836519.0,4.220057e+09,1.320531e+07
351143,2023-08-25,鸿蒙概念,21.165000,21.756944,22.165278,20.919167,8617783.0,1.254978e+10,5.845514e+07
351144,2023-08-25,麒麟电池,47.365000,47.648333,48.055000,46.843333,534960.0,2.976663e+09,6.798281e+05
351145,2023-08-25,黄金概念,11.033208,11.125660,11.264340,10.897358,12888744.0,1.008243e+10,4.770991e+07
351146,2023-08-25,黑龙江板块,10.949487,11.061026,11.271795,10.828974,9001625.0,5.135158e+09,6.593702e+07

In [8]:
df = pd.DataFrame({"stockCode":["0001","0001","0002","0002"],"feature":[1,2,3,4]})

In [9]:
df

  stockCode  feature
0      0001        1
1      0001        2
2      0002        3
3      0002        4

In [12]:
df.groupby("stockCode").apply(lambda x:x.index.to_list()).reset_index()

  stockCode       0
0      0001  [0, 1]
1      0002  [2, 3]

In [14]:
class A:
    @staticmethod
    def f():
        pass

In [15]:
for i, e in enumerate([0,1,2]):
    pass

In [ ]:
# t=0, (0,0)  action = {w,s,a,d,None}~1/5. T = n, E[distance]
# E[(x_n+1,y_n+1)|(xn,yn)] = 1/5( (xn,yn + 1) + (xn,yn - 1) + (xn +1,yn) 
# P(x,y) = count(path to x,y)/5^n
# Target: count(path to x,y)

In [16]:
# matrix = [[]], 0 emtpy,1 target, 2 bad target T=0 M0
# 2 will switch 1->2 M1
# T_inf 1 exists, return -1

In [17]:
M0 = [[0,1,0,0],[0,1,1,0],[0,2,1,0],[0,1,1,1]]
# Target T

In [18]:
    # for i in M:
    #     for j in M[i]:
    #         if M[i][j] == 2:
    #             break

# bfs instead of dfs
def f(M):
    # for _ in range(len(M)):
    #     for 
    f()

def dfs(M, i,j,fs):
    if i==len(M) or j==len(M[0]):
        return -1

    if fs[i][j] == -1:    
        fs[i][j] =  
    
    return fs[i][j]

# f(M) -> is 1, compare with count 1
# f(M) = f(M,i+1,j)==1 ..

In [ ]:
int i;